inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - doc/examples/**/*

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Layout/LineLength:
  Max: 146

Metrics/AbcSize:
  Max: 116

Metrics/BlockLength:
  Max: 27

Metrics/BlockNesting:
  Max: 7

Metrics/ClassLength:
  Max: 389

Metrics/CyclomaticComplexity:
  Max: 44

Metrics/MethodLength:
  Max: 90

Metrics/PerceivedComplexity:
  Max: 45

RSpec/ExampleLength:
  Max: 83

RSpec/MultipleExpectations:
  Max: 28

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
